### PR TITLE
Reflects changes made in DDLC v1.1.1

### PR DESCRIPTION
**Pull request by proudust**

### CODE REVIEW

**Comment by ThePotatoGuy** [comment]
Does not having these changes cause any crashes/issues with the template?

I'm expecting that more people will be using the [mod template from gangstakingofsa](https://github.com/GanstaKingofSA/DDLCModTemplate2.0) rather than this one, so not sure if its worth 3k lines of changes.

I will try and get some people to test this though.

**Comment by proudust** [comment]
I helped develop a MOD using this template called [Blinky Flappers!](https://www.reddit.com/r/DDLCMods/comments/gkuphe/blinky_flappers_adds_some_animationlike_face/?utm_medium=android_app&utm_source=share).
At that time, we found a glitch that was caused by an older version of the template, so we sent a PR.

However, if you want us to use the template by GanstaKingofSA in the future, we will do so.

**Comment by ThePotatoGuy** [comment]
What is the glitch that occurred and what was the cause?

**Comment by proudust** [comment]
When I installed Blinky Flappers! v1, the game content became equivalent to DDLC v1.1.0.
As a result, bugs and typos fixed in DDLC v1.1.1 were reoccurring.
It also affected the behavior when used with the translation MOD for DDLC v1.1.1.

**Pull request closed without merging**
